
hashtable: hashtable.c hashtable.h
	gcc -Wall -o hashtable hashtable.c

bstree: bstree.c bstree.h
	gcc -Wall -o bstree bstree.c

run_hashtable: hashtable
	./hashtable

run_bstree: bstree
	./bstree

clean:
	rm -rf hashtable bstree
